a = input('Digite algo: ')
print('O tipo primitivo desse valor é ', type(a))
print('Só tem espaços? ', a.isspace())
print('é um numero? ', a.isnumeric())
print('é alfabetico? ', a.isalpha())
print('Está em maiusculas? ', a.isupper())
print('Está em minusculo? ', a.islower())
print('Esta capitalizado? ', a.istitle())